-- Initial PostgreSQL schema for MealCraft.
-- Do not edit this migration after it has been applied. Add a new V<number>__*.sql
-- file for every later schema change.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    diet_type VARCHAR(255),
    allergies VARCHAR(255)[],
    preferred_cuisine VARCHAR(100),
    max_cook_time_minutes INTEGER,
    CONSTRAINT uk_user_preferences_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_preferences_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    title VARCHAR(300) NOT NULL,
    ingredients JSONB NOT NULL,
    steps JSONB NOT NULL,
    cuisine VARCHAR(100),
    estimated_time_minutes INTEGER,
    estimated_calories INTEGER,
    source VARCHAR(255),
    tags VARCHAR(255)[],
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_recipes_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE meal_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    week_start_date DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_meal_plans_user_week UNIQUE (user_id, week_start_date),
    CONSTRAINT fk_meal_plans_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE meal_plan_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_plan_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    day_of_week VARCHAR(255),
    meal_type VARCHAR(255),
    CONSTRAINT uk_meal_plan_entries_slot UNIQUE (meal_plan_id, day_of_week, meal_type),
    CONSTRAINT fk_meal_plan_entries_plan
        FOREIGN KEY (meal_plan_id) REFERENCES meal_plans (id),
    CONSTRAINT fk_meal_plan_entries_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (id)
);

CREATE TABLE pantry_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ingredient_name VARCHAR(200) NOT NULL,
    quantity VARCHAR(50),
    unit VARCHAR(50),
    CONSTRAINT uk_pantry_items_user_ingredient UNIQUE (user_id, ingredient_name),
    CONSTRAINT fk_pantry_items_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE shopping_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    meal_plan_id BIGINT,
    generated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_shopping_lists_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_shopping_lists_meal_plan
        FOREIGN KEY (meal_plan_id) REFERENCES meal_plans (id)
);

CREATE TABLE shopping_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id BIGINT NOT NULL,
    ingredient_name VARCHAR(200) NOT NULL,
    quantity VARCHAR(50),
    unit VARCHAR(50),
    is_checked BOOLEAN NOT NULL,
    CONSTRAINT fk_shopping_list_items_list
        FOREIGN KEY (shopping_list_id) REFERENCES shopping_lists (id)
);

CREATE TABLE cooking_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    cooked_at TIMESTAMP(6) NOT NULL,
    notes TEXT,
    CONSTRAINT fk_cooking_history_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_cooking_history_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (id)
);

CREATE TABLE ai_usage_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    usage_date DATE NOT NULL,
    call_count INTEGER NOT NULL,
    CONSTRAINT uk_ai_usage_log_user_date UNIQUE (user_id, usage_date),
    CONSTRAINT fk_ai_usage_log_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_recipes_user_id ON recipes (user_id);
CREATE INDEX idx_meal_plans_user_id ON meal_plans (user_id);
CREATE INDEX idx_pantry_items_user_id ON pantry_items (user_id);
CREATE INDEX idx_shopping_lists_user_id ON shopping_lists (user_id);
CREATE INDEX idx_cooking_history_user_id ON cooking_history (user_id);
CREATE INDEX idx_ai_usage_log_user_id ON ai_usage_log (user_id);
